/*
	This file is part of cpp-elementrem.

	cpp-elementrem is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	cpp-elementrem is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with cpp-elementrem.  If not, see <http://www.gnu.org/licenses/>.
*/
/** @file MixClient.h
 * @
 * 
 * 
 * Elementrem IDE client.
 */

#pragma once

#include <vector>
#include <string>
#include <libelecore/SealEngine.h>
#include <libelementrem/ExtVM.h>
#include <libelementrem/ClientBase.h>
#include <libelementrem/Client.h>
#include "MachineStates.h"

namespace dev
{
namespace ele { class EnvInfo; }

namespace mix
{

class MixBlockChain: public dev::ele::BlockChain
{
public:
	MixBlockChain(std::string const& _path, ele::AccountMap const& _pre);

	static ele::ChainParams createParams(ele::AccountMap const& _pre);
};

class MixClient: public dev::ele::ClientBase
{
public:
	MixClient(std::string const& _dbPath);
	virtual ~MixClient();

	/// Reset state to the empty state with given balance.
	void resetState(dev::ele::AccountMap const& _pre, Secret const& _miner = Secret());
	void mine();
	ExecutionResult lastExecution() const;
	ExecutionResult execution(unsigned _index) const;

	dev::ele::ExecutionResult call(
		Address const& _secret,
		u256 _value,
		Address _dest,
		bytes const& _data,
		u256 _gas, u256 _gasPrice,
		ele::BlockNumber _blockNumber = ele::PendingBlock,
		ele::FudgeFactor _ff = ele::FudgeFactor::Strict
	) override;
	dev::ele::ExecutionResult create(
		Address const& _secret,
		u256 _value,
		bytes const& _data = bytes(),
		u256 _gas = 10000,
		u256 _gasPrice = 10 * ele::szabo,
		ele::BlockNumber _blockNumber = ele::PendingBlock,
		ele::FudgeFactor _ff = ele::FudgeFactor::Strict
	) override;

	using ClientBase::submitTransaction;
	virtual std::pair<h256, Address> submitTransaction(ele::TransactionSkeleton const& _ts, Secret const& _secret) override;
	std::pair<h256, Address> submitTransaction(ele::TransactionSkeleton const& _ts, Secret const& _secret, bool _gasAuto);
	dev::ele::ExecutionResult call(
		Address const& _secret,
		u256 _value,
		Address _dest,
		bytes const& _data,
		u256 _gas,
		u256 _gasPrice,
		ele::BlockNumber _blockNumber,
		bool _gasAuto,
		ele::FudgeFactor _ff = ele::FudgeFactor::Strict
	);
	ExecutionResult debugTransaction(dev::ele::Transaction const& _t, ele:: State const& _state, ele::EnvInfo const& _envInfo, bool _call);
	void setAuthor(Address const& _us) override;
	void startSealing() override {}
	void stopSealing() override {}
	virtual void flushTransactions() override {}

	/// @returns the last mined block information
	using Interface::blockInfo; // to remove warning about hiding virtual function
	ele::BlockHeader blockInfo() const;

	/// return the new address generated by the last tr (if creation). returns empty address if other cases.
	Address lastCreatedContractAddr() const;
	/// Get the storage for the given address
	std::unordered_map<u256, u256> contractStorage(Address _contract);

protected:
	/// ClientBase methods
	using ClientBase::asOf;
	virtual dev::ele::Block asOf(h256 const& _block) const override;
	virtual dev::ele::BlockChain& bc() override { return *m_bc; }
	virtual dev::ele::BlockChain const& bc() const override { return *m_bc; }
	virtual dev::ele::Block preSeal() const override { ReadGuard l(x_state);  return m_preSeal; }
	virtual dev::ele::Block postSeal() const override { ReadGuard l(x_state); return m_postSeal; }
	virtual void prepareForTransaction() override {}

private:
	void executeTransaction(dev::ele::Transaction const& _t, ele::Block& _block, bool _call, bool _gasAuto, dev::Secret const& _secret = dev::Secret());
	dev::ele::Transaction replaceGas(dev::ele::Transaction const& _t, dev::u256 const& _gas, dev::Secret const& _secret = dev::Secret());

	ele::Block m_preSeal;
	ele::Block m_postSeal;
	OverlayDB m_stateDB;
	std::unique_ptr<MixBlockChain> m_bc;
	mutable boost::shared_mutex x_state;
	mutable boost::shared_mutex x_executions;
	ExecutionResults m_executions;
	std::string m_dbPath;
};

}

}
